backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "static/img"
collections:
  -   name: "pages"
      label: "Seiten"
      files:
      - file: "content/_index.md"
        label: "Startseite"
        name: "home"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "content/datenschutz.md"
        label: "Datenschutz"
        name: "datenschutz"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" } 
      - file: "content/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/impressum.md"
        label: "Impressum"
        name: "Impressum"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/links.md"
        label: "Links"
        name: "links"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/rundgang.md"
        label: "Rundgang"
        name: "rundgang"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "body", name: "body", widget: "markdown" } 
      - file: "content/referenzen/waschtische.md"
        label: "Waschtische"
        name: "waschtische"
        editor: 
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Gallery",name: "galleryImages",widget: "list",summary: '{{fields.image}}'}
        field: {label: Image, name: image, widget: image}     
          
                            
      
          
