backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img"
collections:
  -   name: "pages"
      label: "Seitenübersicht"
      - file: "content/_index.md"
        label: "Startseite"
        name: "Startseite"
        editor: 
          preview: false
        fields:
          - { label: "Überschrift", name: "title", widget: "string" }
          - { label: "Editor", name: "body", widget: "markdown" }
      - file: "content/datenschutz.md"
        label: "Datenschutz"
        name: "Datenschutz"
        editor: 
          preview: false
        fields:
          - { label: "Überschrift", name: "title", widget: "string" }
          - { label: "Editor", name: "body", widget: "markdown" } 
      - file: "content/kontakt.md"
        label: "Kontakt"
        name: "Kontakt"
        editor: 
          preview: false
        fields:
          - { label: "Überschrift", name: "title", widget: "string" }
          - { label: "Editor", name: "body", widget: "markdown" }
      - file: "content/impressum.md"
        label: "Impressum"
        name: "Impressum"
        editor: 
          preview: false
        fields:
          - { label: "Überschrift", name: "title", widget: "string" }
          - { label: "Editor", name: "body", widget: "markdown" }
      - file: "content/links.md"
        label: "Links"
        name: "Links"
        editor: 
          preview: false
        fields:
          - { label: "Überschrift", name: "title", widget: "string" }
          - { label: "Editor", name: "body", widget: "markdown" }               
      
          
